# Generated by Django 4.2.15 on 2024-08-11 18:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SS_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_column='user_name', max_length=225)),
                ('category', models.IntegerField(db_column='category')),
                ('active_status', models.BooleanField(db_column='active_status', default=True)),
                ('login_time', models.CharField(blank=True, max_length=225, null=True)),
                ('email', models.CharField(db_column='email', max_length=255, unique=True)),
                ('password', models.CharField(db_column='password', max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
            options={
                'verbose_name_plural': 'SS_User',
                'db_table': 'SS_User',
            },
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[(1, 'request sent'), (2, 'request pending'), (3, 'accepted'), (4, 'rejected'), (5, 'cancelled')], default='request sent', max_length=20),
        ),
        migrations.AlterModelTable(
            name='friendrequest',
            table='FriendRequest',
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='userdetails.ss_user'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='userdetails.ss_user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
