# Generated by Django 4.2.15 on 2024-08-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_ss_user_alter_friendrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'request sent'), (2, 'request pending'), (3, 'accepted'), (4, 'rejected'), (5, 'cancelled')], default='request sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='ss_user',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
