# Generated by Django 4.2.15 on 2024-08-12 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0003_alter_friendrequest_status_alter_ss_user_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[(1, 'request sent'), (2, 'request pending'), (3, 'accepted'), (4, 'rejected'), (5, 'cancelled')], default='request sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='ss_user',
            name='category',
            field=models.IntegerField(choices=[(1, 'user'), (2, 'admin'), (3, 'moderator')], db_column='category'),
        ),
        migrations.AlterField(
            model_name='ss_user',
            name='password',
            field=models.CharField(db_column='password', max_length=128, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
