# Generated by Django 4.2.15 on 2024-08-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0004_alter_friendrequest_status_alter_ss_user_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='friend_of', to='userdetails.friendslist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friends_list', to='userdetails.ss_user')),
            ],
            options={
                'db_table': 'FriendsList',
            },
        ),
    ]
