# Generated by Django 4.2.15 on 2024-08-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0005_friendslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendslist',
            name='friends',
            field=models.ManyToManyField(related_name='friend_of', to='userdetails.ss_user'),
        ),
    ]
